/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimRouteImport } from './routes/tim'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWargaRouteImport } from './routes/_app.warga'
import { Route as AppPetugasRouteImport } from './routes/_app.petugas'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPetugasIndexRouteImport } from './routes/_app.petugas.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppPetugasProfileRouteImport } from './routes/_app.petugas.profile'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminRoadsRouteImport } from './routes/_app.admin.roads'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminProfileRouteImport } from './routes/_app.admin.profile'
import { Route as AppAdminPetugasRouteImport } from './routes/_app.admin.petugas'
import { Route as AppAdminReportsIndexRouteImport } from './routes/_app.admin.reports.index'
import { Route as AppAdminReportsIdRouteImport } from './routes/_app.admin.reports.$id'

const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWargaRoute = AppWargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => AppRoute,
} as any)
const AppPetugasRoute = AppPetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPetugasIndexRoute = AppPetugasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPetugasRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPetugasProfileRoute = AppPetugasProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppPetugasRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRoadsRoute = AppAdminRoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProfileRoute = AppAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPetugasRoute = AppAdminPetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsIndexRoute = AppAdminReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminReportsRoute,
} as any)
const AppAdminReportsIdRoute = AppAdminReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/petugas': typeof AppPetugasRouteWithChildren
  '/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/petugas': typeof AppAdminPetugasRoute
  '/admin/profile': typeof AppAdminProfileRoute
  '/admin/reports': typeof AppAdminReportsRouteWithChildren
  '/admin/roads': typeof AppAdminRoadsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/petugas/profile': typeof AppPetugasProfileRoute
  '/admin/': typeof AppAdminIndexRoute
  '/petugas/': typeof AppPetugasIndexRoute
  '/admin/reports/$id': typeof AppAdminReportsIdRoute
  '/admin/reports/': typeof AppAdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/petugas': typeof AppAdminPetugasRoute
  '/admin/profile': typeof AppAdminProfileRoute
  '/admin/roads': typeof AppAdminRoadsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/petugas/profile': typeof AppPetugasProfileRoute
  '/admin': typeof AppAdminIndexRoute
  '/petugas': typeof AppPetugasIndexRoute
  '/admin/reports/$id': typeof AppAdminReportsIdRoute
  '/admin/reports': typeof AppAdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/petugas': typeof AppPetugasRouteWithChildren
  '/_app/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/admin/petugas': typeof AppAdminPetugasRoute
  '/_app/admin/profile': typeof AppAdminProfileRoute
  '/_app/admin/reports': typeof AppAdminReportsRouteWithChildren
  '/_app/admin/roads': typeof AppAdminRoadsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/petugas/profile': typeof AppPetugasProfileRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/petugas/': typeof AppPetugasIndexRoute
  '/_app/admin/reports/$id': typeof AppAdminReportsIdRoute
  '/_app/admin/reports/': typeof AppAdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/admin'
    | '/petugas'
    | '/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/roads'
    | '/admin/settings'
    | '/admin/users'
    | '/petugas/profile'
    | '/admin/'
    | '/petugas/'
    | '/admin/reports/$id'
    | '/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/roads'
    | '/admin/settings'
    | '/admin/users'
    | '/petugas/profile'
    | '/admin'
    | '/petugas'
    | '/admin/reports/$id'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/_app/admin'
    | '/_app/petugas'
    | '/_app/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/admin/petugas'
    | '/_app/admin/profile'
    | '/_app/admin/reports'
    | '/_app/admin/roads'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/petugas/profile'
    | '/_app/admin/'
    | '/_app/petugas/'
    | '/_app/admin/reports/$id'
    | '/_app/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FiturRoute: typeof FiturRoute
  TentangRoute: typeof TentangRoute
  TimRoute: typeof TimRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warga': {
      id: '/_app/warga'
      path: '/warga'
      fullPath: '/warga'
      preLoaderRoute: typeof AppWargaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/petugas': {
      id: '/_app/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof AppPetugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/petugas/': {
      id: '/_app/petugas/'
      path: '/'
      fullPath: '/petugas/'
      preLoaderRoute: typeof AppPetugasIndexRouteImport
      parentRoute: typeof AppPetugasRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/petugas/profile': {
      id: '/_app/petugas/profile'
      path: '/profile'
      fullPath: '/petugas/profile'
      preLoaderRoute: typeof AppPetugasProfileRouteImport
      parentRoute: typeof AppPetugasRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roads': {
      id: '/_app/admin/roads'
      path: '/roads'
      fullPath: '/admin/roads'
      preLoaderRoute: typeof AppAdminRoadsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/profile': {
      id: '/_app/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AppAdminProfileRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/petugas': {
      id: '/_app/admin/petugas'
      path: '/petugas'
      fullPath: '/admin/petugas'
      preLoaderRoute: typeof AppAdminPetugasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports/': {
      id: '/_app/admin/reports/'
      path: '/'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AppAdminReportsIndexRouteImport
      parentRoute: typeof AppAdminReportsRoute
    }
    '/_app/admin/reports/$id': {
      id: '/_app/admin/reports/$id'
      path: '/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AppAdminReportsIdRouteImport
      parentRoute: typeof AppAdminReportsRoute
    }
  }
}

interface AppAdminReportsRouteChildren {
  AppAdminReportsIdRoute: typeof AppAdminReportsIdRoute
  AppAdminReportsIndexRoute: typeof AppAdminReportsIndexRoute
}

const AppAdminReportsRouteChildren: AppAdminReportsRouteChildren = {
  AppAdminReportsIdRoute: AppAdminReportsIdRoute,
  AppAdminReportsIndexRoute: AppAdminReportsIndexRoute,
}

const AppAdminReportsRouteWithChildren = AppAdminReportsRoute._addFileChildren(
  AppAdminReportsRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminPetugasRoute: typeof AppAdminPetugasRoute
  AppAdminProfileRoute: typeof AppAdminProfileRoute
  AppAdminReportsRoute: typeof AppAdminReportsRouteWithChildren
  AppAdminRoadsRoute: typeof AppAdminRoadsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminPetugasRoute: AppAdminPetugasRoute,
  AppAdminProfileRoute: AppAdminProfileRoute,
  AppAdminReportsRoute: AppAdminReportsRouteWithChildren,
  AppAdminRoadsRoute: AppAdminRoadsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPetugasRouteChildren {
  AppPetugasProfileRoute: typeof AppPetugasProfileRoute
  AppPetugasIndexRoute: typeof AppPetugasIndexRoute
}

const AppPetugasRouteChildren: AppPetugasRouteChildren = {
  AppPetugasProfileRoute: AppPetugasProfileRoute,
  AppPetugasIndexRoute: AppPetugasIndexRoute,
}

const AppPetugasRouteWithChildren = AppPetugasRoute._addFileChildren(
  AppPetugasRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppPetugasRoute: typeof AppPetugasRouteWithChildren
  AppWargaRoute: typeof AppWargaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppPetugasRoute: AppPetugasRouteWithChildren,
  AppWargaRoute: AppWargaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FiturRoute: FiturRoute,
  TentangRoute: TentangRoute,
  TimRoute: TimRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
