/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimRouteImport } from './routes/tim'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWargaRouteImport } from './routes/_app.warga'
import { Route as AppPetugasRouteImport } from './routes/_app.petugas'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminReportsIdRouteImport } from './routes/_app.admin.reports.$id'

const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWargaRoute = AppWargaRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => AppRoute,
} as any)
const AppPetugasRoute = AppPetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsIdRoute = AppAdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/petugas': typeof AppPetugasRoute
  '/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/reports/$id': typeof AppAdminReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/petugas': typeof AppPetugasRoute
  '/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/reports/$id': typeof AppAdminReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/fitur': typeof FiturRoute
  '/tentang': typeof TentangRoute
  '/tim': typeof TimRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/petugas': typeof AppPetugasRoute
  '/_app/warga': typeof AppWargaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/reports/$id': typeof AppAdminReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/admin'
    | '/petugas'
    | '/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/users'
    | '/admin/'
    | '/admin/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/petugas'
    | '/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/users'
    | '/admin'
    | '/admin/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/fitur'
    | '/tentang'
    | '/tim'
    | '/_app/admin'
    | '/_app/petugas'
    | '/_app/warga'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/admin/users'
    | '/_app/admin/'
    | '/_app/admin/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FiturRoute: typeof FiturRoute
  TentangRoute: typeof TentangRoute
  TimRoute: typeof TimRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warga': {
      id: '/_app/warga'
      path: '/warga'
      fullPath: '/warga'
      preLoaderRoute: typeof AppWargaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/petugas': {
      id: '/_app/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof AppPetugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports/$id': {
      id: '/_app/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AppAdminReportsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminReportsIdRoute: typeof AppAdminReportsIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminReportsIdRoute: AppAdminReportsIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppPetugasRoute: typeof AppPetugasRoute
  AppWargaRoute: typeof AppWargaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppPetugasRoute: AppPetugasRoute,
  AppWargaRoute: AppWargaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FiturRoute: FiturRoute,
  TentangRoute: TentangRoute,
  TimRoute: TimRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
